### ISSUE TITLE
[Question] Add language selector 

### ISSUE THREAD

**Issue by coin3x** [Sonelli/juicessh-translations#47]
Some people want a language selector, Please add it!

**Comment by radicspeter** [comment]
Good idea +1 ;)

**Comment by ChlupataKulicka** [comment]
yeah, +1

**Comment by reBirthLab** [comment]
By the way, if one translates to a different language than the device language, one wouldn't be able to test the translation. Would be great to have even in testing purposes.

**Comment by edumardo** [comment]
+1, perfect to check the translation "online".

**Comment by radicspeter** [comment]
YES, all of the translators and all of the users have a good chance to check JuiceSSH in original language and their local language meaning differences.
By the way, i am finishing hungarian language translate, and if this idea will be in JuiceSSH, users can easier contact translators, if in they translate is not perfect... 
So be consider this good idea. ;)

Peter, from Hungary.

**Comment by PaulMaddox** [comment]
While I agree this would be nice to have, unfortunately Android doesn't provide any built in way of achieving this with it's [standard localisation](http://developer.android.com/training/basics/supporting-devices/languages.html). Apps will always use the built in system language.

There are a few solutions for this online, however most of the ones i've seen are hacks around this lack of built in functionality, and are often buggy (eg language choice is lost whenever device is rotated). I don't feel comfortable including something like this into JuiceSSH with such a large user base that could be impacted.

I think for the time being, the best option for testing while working on translations is to actually set your device language to the target language.
