### ISSUE TITLE
Word context needed for translation

### ISSUE THREAD

**Issue by RaphaelRochet** [Sonelli/juicessh-translations#6]
Can you give me an hint on where are these strings used ?
```  
	<string name="forward">
    <string name="confirm">
```

**Comment by RaphaelRochet** [comment]
Also for this one :
```respond```

**Comment by PaulMaddox** [comment]
``` <string name="forward">```
Is used as a button context description (for accessibility etc) on a button that advances to the next page

```<string name="confirm">```
Is used on a popup dialog that asks "Are you sure you want to clear your snippets?"

```<string name="respond">```
Is shown when a user has a new invitation to join a team, and they can click to respond to the invitation

**Comment by RaphaelRochet** [comment]
Thanks
Does "respond" mean to accept the invitation ? (Never use that feature, sorry)

**Comment by PaulMaddox** [comment]
It doesn't necessarily imply accept. The user could accept or reject the invitation
